-- =====================================================
-- Project: Global Superstore Sales Analysis
-- File: 01_Business_Queries.sql
-- Module: Basic Business Queries
-- =====================================================



-- =====================================================
-- Question 1
-- Business Requirement:
-- The Sales Manager wants to know the total sales
-- generated in each region.
-- =====================================================
SELECT 
region,
SUM(sales) AS total_sales 
FROM global_superstore
GROUP BY region;

-- =====================================================
-- Question 2
-- Business Requirement:
-- The Finance Manager wants to know the total profit
-- earned from each category.
-- =====================================================
SELECT 
category,
SUM(profit) AS total_profit
FROM global_superstore
GROUP BY category;

-- =====================================================
-- Question 3
-- Business Requirement:
-- The Sales Manager wants to identify the top 10 customers
-- based on the total sales they have generated.
-- =====================================================
SELECT 
customer_name,
SUM(sales) AS total_sales
FROM global_superstore
GROUP BY customer_name
ORDER BY total_sales DESC
LIMIT 10;

-- =====================================================
-- Question 4
-- Business Requirement:
-- The Inventory Manager wants to identify the top 10
-- products based on the total sales they have generated.
-- =====================================================
SELECT 
product_name,
SUM(sales) AS total_sales
FROM global_superstore
GROUP BY product_name
ORDER BY total_sales DESC
LIMIT 10;


-- =====================================================
-- Question 5
-- Business Requirement:
-- The Marketing Manager wants to know the total sales
-- generated by each customer segment.
-- =====================================================
SELECT 
segment,
SUM(sales) AS total_sales
FROM global_superstore
GROUP BY segment;

-- =====================================================
-- Question 6
-- Business Requirement:
-- The Operations Manager wants to know the total number
-- of orders placed in each region.
-- =====================================================
SELECT 
region,
COUNT(*) AS no_of_orders
FROM global_superstore
GROUP BY region;

-- =====================================================
-- Question 7
-- Business Requirement:
-- The Sales Director wants to know the average sales
-- amount for each category.
-- =====================================================
SELECT 
category,
AVG(sales) AS avg_sales
FROM global_superstore
GROUP BY category;

-- =====================================================
-- Question 8
-- Business Requirement:
-- The Sales Manager wants to identify all regions where
-- the total sales exceed 1,000,000.
-- =====================================================
SELECT 
region,
SUM(sales) AS total_sales
FROM global_superstore
GROUP BY region
HAVING total_sales > 1000000;

-- =====================================================
-- Question 9
-- Business Requirement:
-- The Sales Director wants to identify all customers
-- whose total sales exceed 20,000.
-- =====================================================
SELECT 
customer_name,
SUM(sales) AS total_sales 
FROM global_superstore
GROUP BY customer_name
HAVING total_sales > 20000;

-- =====================================================
-- Question 10
-- Business Requirement:
-- The Finance Manager wants to know the total profit
-- generated by each region, but only include regions
-- where the total profit is greater than 100,000.
-- =====================================================
SELECT
region,
SUM(profit) AS total_profit 
FROM global_superstore
GROUP BY region
HAVING total_profit > 100000;

SELECT * FROM global_superstore;